version: '3.8'
services:
  node-app:
    build: ./dist
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/dist:ro
      - /dist/node_modules
    env_file:
      - ./dist/.env
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
